language: golang
sudo: required

branches:
  only:
    - master

services:
  - docker


script:
  - echo 'Cool'

after_success:
  - chmod +x .travis/create-docker-snapshot.sh
  - .travis/create-docker-snapshot.sh

deploy:
  - provider: script
    script: .travis/create-docker-release.sh
    skip_cleanup: true
    on:
      tags: true
