FROM pdok/gobase
CMD ["/bin/registrator"]

ENV GOPATH /go
COPY . /go/src/github.com/gliderlabs/registrator
RUN cd /go/src/github.com/gliderlabs/registrator \
	&& go get \
	&& go build -ldflags "-X main.Version=dev" -o /bin/registrator
